# Cloudflare Workers configuration
name = "todolist-web"
main = "src/worker.js"
compatibility_date = "2024-09-20"

[observability.logs]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"