server:
  port: ":8080"
  mode: "debug"  # debug 或 release

database:
  type: "sqlite"  # sqlite 或 postgres
  sqlite:
    path: "./data/todolist.db"
  postgres:
    host: "localhost"
    port: 5432
    username: "todolist"
    password: "password"
    database: "todolist"
    sslmode: "disable"

jwt:
  secret: "your-jwt-secret-key-change-this-in-production"
  expires_in: 24  # JWT过期时间，单位：小时

features:
  enable_registration: true  # 是否启用注册功能