version: '3.8'

services:
  # 后端服务
  todolist-backend:
    image: ${DOCKER_USERNAME:-zdwtest}/todolist-backend:${TAG:-latest}
    container_name: todolist-backend
    ports:
      - "8080:8080"
    volumes:
      - todolist_data:/app/data
      - ./backend/config/config.yaml:/app/config/config.yaml:ro
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    networks:
      - todolist-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端服务
  todolist-frontend:
    image: ${DOCKER_USERNAME:-zdwtest}/todolist-frontend:${TAG:-latest}
    container_name: todolist-frontend
    ports:
      - "80:80"
    depends_on:
      todolist-backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - todolist-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL数据库 (可选)
  postgres:
    image: postgres:15-alpine
    container_name: todolist-postgres
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - todolist-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todolist"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis缓存 (可选)
  redis:
    image: redis:7-alpine
    container_name: todolist-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - todolist-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  todolist_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  todolist-network:
    driver: bridge