services:
  todolist-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - todolist_data:/app/data
      - ./backend/config/config.yaml:/app/config/config.yaml:ro
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    networks:
      - todolist-network

  # PostgreSQL数据库 (可选)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - todolist-network
    profiles:
      - postgres

  # Nginx反向代理 (可选)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - todolist-app
    restart: unless-stopped
    networks:
      - todolist-network
    profiles:
      - nginx

volumes:
  todolist_data:
  postgres_data:

networks:
  todolist-network:
    driver: bridge